apiVersion: apps/v1

kind: Deployment

metadata:
    name: expensetracker
    labels:
        app: expensetracker

spec:
    selector:
        matchLabels:
            app: expensetracker
    replicas: 1

    template:
        metadata:
            labels:
                app: expensetracker

        spec:
            containers:
                - name: expensetracker

                  image: icr.io/personal_expense/expensetracker

                  imagePullPolicy: Always

                  ports:
                      - containerPort: 5000
                  env:
                      - name: DISABLE_WEB_APP
                        value: "false"
