FROM python:3.6
WORKDIR /app
ADD . /app
COPY requirements.txt /app
RUN python3 -m pip install -r requirements.txt
RUN python3 -m pip install ibm_db
EXPOSE 5000
CMD ["python","app.py"]

# FROM python:3.10-alpine
# WORKDIR /app
# ADD . /app

# RUN set -e; \
#         apk add --no-cache --virtual .build-deps \
#                 gcc \
#                 libc-dev \
#                 linux-headers \
#                 mariadb-dev \
#                 python3-dev \
#         ;
# COPY requirements.txt /app
# RUN pip3 install -r requirements.txt
# CMD ["python3","app.py"]
Footer
© 2022 GitHub, Inc.
Footer navigation
Terms
